openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/tutorial/1.0.0
    description: SwaggerHub API Auto Mocking
paths:
  /student/{student_id}:
    get:
      summary: Get student
      description: Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: The student's unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        "400":
          description: Invalid ID
        "404":
          description: Not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: Delete student
      description: Deletes a single student
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: The uid
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: Student deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request - Invalid student_id format
        "404":
          description: Student with specified student_id cannot be found
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds a student to the system
      operationId: add_student
      requestBody:
        description: Student object to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                example: 123e4567-e89b-12d3-a456-426614174000
                x-content-type: application/json
        "400":
          description: "Invalid input, object invalid"
        "409":
          description: Already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      required:
      - first_name
      - grade_records
      - last_name
      - student_id
      type: object
      properties:
        student_id:
          type: number
          format: integer
          example: 12345
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        grade_records:
          type: array
          items:
            $ref: '#/components/schemas/GradeRecord'
      example:
        student_id: 12345
        last_name: Doe
        grade_records:
        - grade: 8.5
          subject_name: Mathematics
        - grade: 8.5
          subject_name: Mathematics
        first_name: John
    GradeRecord:
      required:
      - grade
      - subject_name
      type: object
      properties:
        subject_name:
          type: string
          example: Mathematics
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
          example: 8.5
      example:
        grade: 8.5
        subject_name: Mathematics
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: Student deleted successfully
      example:
        message: Student deleted successfully

